import './doriosAPI/main.js'

import './config/main.js'

import './blocks/bonsai.js'
import './blocks/cobble_generators.js'
import './blocks/crucible.js'
import './blocks/sieve.js'
import './blocks/crops.js'
import './blocks/light_blocks.js'
import './blocks/on_interact.js'
import './blocks/asphalt.js'
import './blocks/elevator.js'
import './blocks/xp_magnet.js'
import './blocks/xp.js'
import './blocks/mob_grinder.js'
import './blocks/pedestal.js'
import './blocks/fan.js'
import './blocks/mech_spawners.js'

import './items/durability.js'
import './items/drill.js'
import './items/block_loot.js'
import './items/hammer.js'
import './items/dig_pebble.js'
import './items/smelting.js'
import './items/potion.js'
import './items/hoe.js'
import './items/essences.js'
import './items/arm.js'

import './stack_refill.js'

import './machinery/main.js'

import './speed.js'