clear @a twm:energy_bar_0
clear @a twm:energy_bar_1
clear @a twm:energy_bar_2
clear @a twm:energy_bar_3
clear @a twm:energy_bar_4
clear @a twm:energy_bar_5
clear @a twm:energy_bar_6
clear @a twm:energy_bar_7
clear @a twm:energy_bar_8
clear @a twm:energy_bar_9
clear @a twm:energy_bar_10
clear @a twm:energy_bar_11
clear @a twm:energy_bar_12
clear @a twm:energy_bar_13
clear @a twm:energy_bar_14
clear @a twm:energy_bar_15
clear @a twm:energy_bar_16

clear @a twm:water_bar_0
clear @a twm:water_bar_1
clear @a twm:water_bar_2
clear @a twm:water_bar_3
clear @a twm:water_bar_4
clear @a twm:water_bar_5
clear @a twm:water_bar_6
clear @a twm:water_bar_7
clear @a twm:water_bar_8
clear @a twm:water_bar_9
clear @a twm:water_bar_10
clear @a twm:water_bar_11
clear @a twm:water_bar_12
clear @a twm:water_bar_13
clear @a twm:water_bar_14
clear @a twm:water_bar_15
clear @a twm:water_bar_16

clear @a twm:lava_bar_0
clear @a twm:lava_bar_1
clear @a twm:lava_bar_2
clear @a twm:lava_bar_3
clear @a twm:lava_bar_4
clear @a twm:lava_bar_5
clear @a twm:lava_bar_6
clear @a twm:lava_bar_7
clear @a twm:lava_bar_8
clear @a twm:lava_bar_9
clear @a twm:lava_bar_10
clear @a twm:lava_bar_11
clear @a twm:lava_bar_12
clear @a twm:lava_bar_13
clear @a twm:lava_bar_14
clear @a twm:lava_bar_15
clear @a twm:lava_bar_16
