import './machines/autosieve.js'
import './machines/seed_synthesizer.js'
import './machines/simple_machine.js'
import './machines/double_machine.js'
import './machines/block_breaker.js'
import './machines/block_placer.js'
import './machines/induction_anvil.js'
import './machines/digitizer.js'
import './machines/assembler.js'
import './machines/harvester.js'
import './managers.js'

import './upgradeable.js'