import './machines/autosieve.js'
import './machines/seed_synthesizer.js'
import './machines/simple_machine.js'
import './machines/simple_machine_liquid.js'
import './machines/double_machine.js'
import './machines/block_breaker.js'
import './machines/block_placer.js'
import './machines/induction_anvil.js'
import './machines/digitizer.js'
import './machines/assembler.js'
import './machines/harvester.js'
import './machines/way_center.js'
import './machines/xp_condenser.js'

import './generators/furnator.js'
import './generators/solar_panel.js'
import './generators/magmator.js'
import './generators/thermo_generator.js'
import './generators/battery.js'

import './transfer_system/system.js'

import './managers.js'
import './upgradeable.js'
import './fluid_containers.js'